# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
  # First job in workflow called "Dev" 
  Dev:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a nutter tests
      - name: Run Nutter tests
        run: |
          pip install nutter
  
          export DATABRICKS_HOST=https://adb-4821230018992413.13.azuredatabricks.net
          export DATABRICKS_TOKEN=dapi88db6a2de5efa0fc1955cba77c061479-2
  
          nutter run /Repos/andreas.forsberg@capgemini.com/test_cicd/dev_dir/nutter_test --cluster_id 0826-123427-50uwyk9k -timeout 1000
          
  # Second job workflow called "Test" 
  Test:
    needs: Dev
    
    runs-on: ubuntu-latest
    
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Push code from dev to test branch
      - name: Pusch code from Dev to Test branch
        run: |
          git checkout Test
          git push test_cicd Test
