name: CICD workflow

on:
  push:
    branches:
      - Dev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  Dev:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Nutter tests
        run: |
          pip install nutter
  
          export DATABRICKS_HOST=https://adb-4821230018992413.13.azuredatabricks.net
          export DATABRICKS_TOKEN=dapi88db6a2de5efa0fc1955cba77c061479-2
  
          nutter run /Repos/andreas.forsberg@capgemini.com/test_cicd/dev_dir/nutter_test --cluster_id 0826-123427-50uwyk9k -timeout 1000

  Test:
    needs: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Push code from Dev to Test branch
        run: |
          git checkout -B Test ${{ github.sha }}
          git push origin Test
